services:
  - type: web
    name: trading-assistant-all-in-one
    env: docker
    plan: free
    region: singapore
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: IS_VIRTUAL
        value: "True"
      - key: TARGET_MARKET
        value: "US"
      - key: GEMINI_API_KEY
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
